name: Deploy TensorBoard Logs to GitHub Pages

on:
  push:
    branches:
      - feat/profiler

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TensorBoard
        run: pip install torch torchvision tensorboard

      - name: Convert logs to static site
        run: |
          tensorboard --logdir logs --port 6006 &
          sleep 10
          wget -r -np -nH --cut-dirs=3 -P ./tensorboard_site http://localhost:6006/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tensorboard_site
